blank_issues_enabled: false
contact_links:
  - name: StartGPT support
    url: https://help.openai.com/
    about: |
      Please only file issues here that you believe represent actual bugs or feature requests for the StartGPT Node library.
      If you're having general trouble with the StartGPT API, please visit our help center to get support.
